# Generated by Django 4.0.4 on 2022-05-20 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250)),
                ('thumbnail', models.URLField(blank=True)),
                ('author', models.CharField(max_length=250)),
                ('published_time', models.DateTimeField()),
                ('content', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=250)),
                ('is_scraping', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('from_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.source')),
                ('topic', models.ForeignKey(default='General', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.topic')),
            ],
        ),
    ]
