# Generated by Django 4.0.4 on 2022-05-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_articlecontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecontent',
            old_name='articles_id',
            new_name='article_id',
        ),
    ]
